# Generated by Django 4.1.2 on 2022-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('1', ' Desenho e Pintura'), ('2', 'Curso de Cerâmica'), ('3', 'Retrato com modelo vivo'), ('4', 'paisagem/3ª idade'), ('5', 'Aquarela (aula quinzenal'), ('6', 'seção modelo vivo')], default='new Curso', max_length=100)),
                ('newItemName', models.CharField(default='New Item', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='curso',
            field=models.CharField(max_length=50),
        ),
    ]
