# Generated by Django 4.1.2 on 2022-11-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_alter_cliente_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='newItemName',
        ),
        migrations.AddField(
            model_name='curso',
            name='novoCurso',
            field=models.CharField(default='Novo Curso', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(choices=[('1', ' Desenho e Pintura'), ('2', 'Curso de cerâmica'), ('3', 'Retrato com modelo vivo'), ('4', 'paisagem/3ª idade'), ('5', 'Aquarela (aula quinzenal'), ('6', 'seção modelo vivo')], default='novo Curso', max_length=100),
        ),
    ]
