# Generated by Django 4.0.5 on 2022-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_curso_newitemname_curso_novocurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(choices=[('1', ' Desenho e Pintura'), ('2', 'Curso de cerâmica'), ('3', 'Retrato com modelo vivo'), ('4', 'paisagem/3ª idade'), ('5', 'Aquarela (aula quinzenal'), ('6', 'seção modelo vivo')], default='Novo Curso', max_length=50),
        ),
    ]
